// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

listener http:Listener ep0 = new (9090);

public type ProblemDetails record {
    string 'type?;
    string title?;
    int status?;
    string detail?;
    string instance?;
};

public type ProblemDetailsNotFound record {|
    *http:NotFound;
    ProblemDetails body;
|};

public type UsageRecordOk record {|
    *http:Ok;
    UsageRecord body;
|};

final readonly & Subscription mockSubscription = {
    organisationId: "9ac2f1d6-5d3e-4b49-9a1b-2f4c7d8e1a20",
    endDate: "2027-09-30T00:00:00Z",
    plans: [
        {
            subscriptionItems: [
                {
                    product: {
                        id: "5a7bb2c0-1c3e-4d6f-8a09-6e1f2d3c4b5a",
                        name: "Analytics Pro",
                        seatUnit: "user",
                        'type: "METERED",
                        usageUnit: "API call"
                    },
                    quantity: 1,
                    endDate: "2027-09-30T00:00:00Z",
                    price: {amount: 29.99, currency: "USD", id: "f3c1d7a2-8b4e-4e0a-9d61-3a7b5c2e9f10"},
                    testMode: true,
                    id: "2d9e4b7a-6c1f-4a83-b5d0-7e8f9a1b2c3d",
                    startDate: "2026-09-30T00:00:00Z",
                    status: "ACTIVE"
                }
            ],
            name: "Analytics Pro Monthly",
            id: "c8b7a6f5-e4d3-4c2b-a190-8f7e6d5c4b3a",
            status: "ACTIVE"
        }
    ],
    currentPeriodEnd: "2026-10-30T00:00:00Z",
    testMode: true,
    id: "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
    startDate: "2026-09-30T00:00:00Z",
    status: "ACTIVE"
};

final readonly & UsageRecord mockUsageRecord = {
    quantity: 25,
    subscriptionItemId: "2d9e4b7a-6c1f-4a83-b5d0-7e8f9a1b2c3d",
    productId: "5a7bb2c0-1c3e-4d6f-8a09-6e1f2d3c4b5a",
    recordedAt: "2026-09-30T10:15:00Z",
    testMode: true,
    usageRecordId: "e7f6a5b4-c3d2-4e1f-a0b9-8c7d6e5f4a3b",
    subscriptionId: "a1b2c3d4-e5f6-4a7b-8c9d-0e1f2a3b4c5d",
    pricePerUnit: 0.25d
};

service / on ep0 {
    # Retrieves a subscription for a given subscriptionId
    #
    # + subscriptionId - Unique identifier for Subscription object
    # + return - returns can be any of following types 
    # http:Ok (Success - return response of unique Subscription object)
    # http:NotFound (When a failure occurs in the endpoint)
    resource function get [string subscriptionId]() returns Subscription|ProblemDetailsNotFound {
        if subscriptionId != mockSubscription.id {
            return {body: {title: "Not Found", status: 404, detail: "Subscription not found"}};
        }
        return mockSubscription;
    }

    # Gets all usage records related to the subscription
    #
    # + subscriptionId - Unique identifier for Subscription object
    # + return - returns can be any of following types 
    # http:Ok (Success - return a list of all usage record submitted against this subscription)
    # http:NotFound (When a failure occurs in the endpoint)
    resource function get [string subscriptionId]/usage\-records() returns UsageRecordsList|ProblemDetailsNotFound {
        if subscriptionId != mockSubscription.id {
            return {body: {title: "Not Found", status: 404, detail: "Subscription not found"}};
        }
        return {usageRecords: [mockUsageRecord]};
    }

    # Send metered usage belonging to this subscription and subscription item
    #
    # + idempotencyKey - This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    # + subscriptionId - Unique identifier for Subscription object
    # + subscriptionItemId - The unique identifier of the subscriptionItem
    # + payload - Contains the quantity for the usage record to create 
    # + return - returns can be any of following types 
    # http:Ok (Success - return response of the record submitted)
    # http:NotFound (When a failure occurs in the endpoint)
    resource function post [string subscriptionId]/items/[string subscriptionItemId]/usage\-records(@http:Header {name: "Idempotency-Key"} string? idempotencyKey, @http:Payload CreateUsageRecordRequest payload) returns UsageRecordOk|ProblemDetailsNotFound {
        if subscriptionId != mockSubscription.id {
            return {body: {title: "Not Found", status: 404, detail: "Subscription not found"}};
        }
        UsageRecord created = {...mockUsageRecord};
        created.quantity = payload.quantity;
        created.recordedAt = payload.timestamp;
        created.subscriptionItemId = subscriptionItemId;
        return {body: created};
    }

    # Update and existing metered usage belonging to this subscription and subscription item
    #
    # + idempotencyKey - This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    # + subscriptionId - Unique identifier for Subscription object
    # + subscriptionItemId - The unique identifier of the subscriptionItem
    # + usageRecordId - The unique identifier of the usage record
    # + payload - Contains the quantity for the usage record to update 
    # + return - returns can be any of following types 
    # http:Ok (Success - return response of the modified record)
    # http:NotFound (When a failure occurs in the endpoint)
    resource function put [string subscriptionId]/items/[string subscriptionItemId]/usage\-records/[string usageRecordId](@http:Header {name: "Idempotency-Key"} string? idempotencyKey, @http:Payload UpdateUsageRecordRequest payload) returns UsageRecord|ProblemDetailsNotFound {
        if subscriptionId != mockSubscription.id {
            return {body: {title: "Not Found", status: 404, detail: "Subscription not found"}};
        }
        UsageRecord updated = {...mockUsageRecord};
        updated.quantity = payload.quantity;
        updated.subscriptionItemId = subscriptionItemId;
        updated.usageRecordId = usageRecordId;
        return updated;
    }
}
