// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/data.jsondata;
import ballerina/http;

# These endpoints are for Xero Partners to interact with the App Store Billing platform
public isolated client class Client {
    final http:Client clientEp;
    # Gets invoked to initialize the `connector`.
    #
    # + config - The configurations to be used when initializing the `connector` 
    # + serviceUrl - URL of the target service 
    # + return - An error if connector initialization failed 
    public isolated function init(ConnectionConfig config, string serviceUrl = "https://api.xero.com/appstore/2.0/subscriptions") returns error? {
        http:ClientConfiguration httpClientConfig = {auth: config.auth, httpVersion: config.httpVersion, http1Settings: config.http1Settings, http2Settings: config.http2Settings, timeout: config.timeout, forwarded: config.forwarded, followRedirects: config.followRedirects, poolConfig: config.poolConfig, cache: config.cache, compression: config.compression, circuitBreaker: config.circuitBreaker, retryConfig: config.retryConfig, cookieConfig: config.cookieConfig, responseLimits: config.responseLimits, secureSocket: config.secureSocket, proxy: config.proxy, socketConfig: config.socketConfig, validation: config.validation, laxDataBinding: config.laxDataBinding};
        self.clientEp = check new (serviceUrl, httpClientConfig);
    }

    # Retrieves a subscription for a given subscriptionId
    #
    # + subscriptionId - Unique identifier for Subscription object
    # + headers - Headers to be sent with the request 
    # + return - Success - return response of unique Subscription object 
    remote isolated function getSubscription(string subscriptionId, map<string|string[]> headers = {}) returns Subscription|error {
        string resourcePath = string `/${getEncodedUri(subscriptionId)}`;
        return self.clientEp->get(resourcePath, headers);
    }

    # Send metered usage belonging to this subscription and subscription item
    #
    # + subscriptionId - Unique identifier for Subscription object
    # + subscriptionItemId - The unique identifier of the subscriptionItem
    # + headers - Headers to be sent with the request 
    # + payload - Contains the quantity for the usage record to create 
    # + return - Success - return response of the record submitted 
    remote isolated function createUsageRecord(string subscriptionId, string subscriptionItemId, CreateUsageRecordRequest payload, CreateUsageRecordHeaders headers = {}) returns UsageRecord|error {
        string resourcePath = string `/${getEncodedUri(subscriptionId)}/items/${getEncodedUri(subscriptionItemId)}/usage-records`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->post(resourcePath, request, httpHeaders);
    }

    # Update and existing metered usage belonging to this subscription and subscription item
    #
    # + subscriptionId - Unique identifier for Subscription object
    # + subscriptionItemId - The unique identifier of the subscriptionItem
    # + usageRecordId - The unique identifier of the usage record
    # + headers - Headers to be sent with the request 
    # + payload - Contains the quantity for the usage record to update 
    # + return - Success - return response of the modified record 
    remote isolated function updateUsageRecord(string subscriptionId, string subscriptionItemId, string usageRecordId, UpdateUsageRecordRequest payload, UpdateUsageRecordHeaders headers = {}) returns UsageRecord|error {
        string resourcePath = string `/${getEncodedUri(subscriptionId)}/items/${getEncodedUri(subscriptionItemId)}/usage-records/${getEncodedUri(usageRecordId)}`;
        map<string|string[]> httpHeaders = http:getHeaderMap(headers);
        http:Request request = new;
        json jsonBody = jsondata:toJson(payload);
        request.setPayload(jsonBody, "application/json");
        return self.clientEp->put(resourcePath, request, httpHeaders);
    }

    # Gets all usage records related to the subscription
    #
    # + subscriptionId - Unique identifier for Subscription object
    # + headers - Headers to be sent with the request 
    # + return - Success - return a list of all usage record submitted against this subscription for this subscription period 
    remote isolated function listUsageRecords(string subscriptionId, map<string|string[]> headers = {}) returns UsageRecordsList|error {
        string resourcePath = string `/${getEncodedUri(subscriptionId)}/usage-records`;
        return self.clientEp->get(resourcePath, headers);
    }
}
