// AUTO-GENERATED FILE. DO NOT MODIFY.
// This file is auto-generated by the Ballerina OpenAPI tool.

// Copyright (c) 2026, WSO2 LLC. (http://www.wso2.com).
//
// WSO2 LLC. licenses this file to you under the Apache License,
// Version 2.0 (the "License"); you may not use this file except
// in compliance with the License.
// You may obtain a copy of the License at
//
// http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing,
// software distributed under the License is distributed on an
// "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
// KIND, either express or implied.  See the License for the
// specific language governing permissions and limitations
// under the License.

import ballerina/http;

# OAuth2 Client Credentials Grant Configs
public type OAuth2ClientCredentialsGrantConfig record {|
    *http:OAuth2ClientCredentialsGrantConfig;
    # Token URL
    string tokenUrl = "https://identity.xero.com/connect/token";
|};

# Represents the Headers record for the operation: createUsageRecord
public type CreateUsageRecordHeaders record {
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
};

# Data transfer object for public create usage end point
public type CreateUsageRecordRequest record {
    # The initial quantity for the usage record. Must be a whole number that is greater than or equal to 0
    int:Signed32 quantity;
    # DateTime in UTC of when the the product was consumed/used
    string timestamp;
};

public type UsageRecord record {
    # The quantity recorded
    int:Signed32 quantity;
    # The unique identifier of the SubscriptionItem
    string subscriptionItemId;
    # The unique identifier of the linked Product
    string productId;
    # The time when this usage was recorded in UTC
    string recordedAt;
    # If the subscription is a test subscription
    boolean testMode;
    # The unique identifier of the usageRecord
    string usageRecordId;
    # The unique identifier of the Subscription
    string subscriptionId;
    # The price per unit
    decimal pricePerUnit;
};

public type Product record {
    # The unique identifier for the product
    string id?;
    # The name of the product
    string name?;
    # The unit of the per seat product. e.g. "user", "organisation", "SMS", etc
    string seatUnit?;
    # The pricing model of the product:
    # * FIXED: Customers are charged a fixed amount for each billing period
    # * PER_SEAT: Customers are charged based on the number of units they purchase
    # * METERED: Customers are charged per use of this product
    # * SIMPLE: Customers are charged on a fixed amount for each billing period with an optional add-on feature
    "FIXED"|"PER_SEAT"|"METERED"|"SIMPLE" 'type?;
    # The unit of the usage product. e.g. "user", "minutes", "SMS", etc
    string usageUnit?;
};

public type Plan record {
    # List of the subscription items belonging to the plan. It does not
    # include cancelled subscription items
    SubscriptionItem[] subscriptionItems;
    # The name of the plan. It is used in the invoice line item
    # description
    string name;
    # The unique identifier of the plan
    string id;
    # Status of the plan. Available statuses are ACTIVE, CANCELED, and
    # PENDING_ACTIVATION
    "ACTIVE"|"CANCELED"|"PENDING_ACTIVATION" status;
};

public type SubscriptionItem record {
    Product product;
    # The quantity of the item. For a fixed product, it is 1. For a per-seat product, it is a positive integer. For metered products, it is always null
    int quantity?;
    # Date when the subscription to this product will end
    string endDate?;
    Price price;
    # If the subscription is a test subscription
    boolean testMode?;
    # The unique identifier of the subscription item
    string id;
    # Date the subscription started, or will start. Note: this could be in
    # the future for downgrades or reduced number of seats that haven't taken effect yet
    string startDate;
    # Status of the subscription item. Available statuses are ACTIVE, CANCELED, and
    # PENDING_ACTIVATION
    "ACTIVE"|"CANCELED"|"PENDING_ACTIVATION" status;
};

# Response to get usage record
public type UsageRecordsList record {
    # A collection of usage records
    UsageRecord[] usageRecords;
};

# Represents the Headers record for the operation: updateUsageRecord
public type UpdateUsageRecordHeaders record {
    # This allows you to safely retry requests without the risk of duplicate processing. 128 character max
    @http:Header {name: "Idempotency-Key"}
    string idempotencyKey?;
};

public type Price record {
    # The net (before tax) amount
    decimal amount;
    # The currency of the price
    string currency;
    # The unique identifier of the price
    string id;
};

# Data transfer object for public update usage end point
public type UpdateUsageRecordRequest record {
    # The new quantity for the usage record. Must be a whole number that is greater than or equal to 0
    int:Signed32 quantity;
};

public type Subscription record {
    # The Xero generated unique identifier for the organisation
    string organisationId;
    # If the subscription has been canceled, this is the date when the subscription ends. If null, the subscription is active and has not been cancelled
    string endDate?;
    # List of plans for the subscription
    Plan[] plans;
    # End of the current period that the subscription has been invoiced for
    string currentPeriodEnd;
    # Boolean used to indicate if the subscription is in test mode
    boolean testMode?;
    # The unique identifier of the subscription
    string id;
    # Date when the subscription was first created
    string startDate;
    # Status of the subscription. Available statuses are ACTIVE, CANCELED, and PAST_DUE
    "ACTIVE"|"CANCELED"|"PAST_DUE" status;
};

# Provides a set of configurations for controlling the behaviours when communicating with a remote HTTP endpoint.
@display {label: "Connection Config"}
public type ConnectionConfig record {|
    # Configurations related to client authentication
    OAuth2ClientCredentialsGrantConfig auth;
    # The HTTP version understood by the client
    http:HttpVersion httpVersion = http:HTTP_2_0;
    # Configurations related to HTTP/1.x protocol
    http:ClientHttp1Settings http1Settings = {};
    # Configurations related to HTTP/2 protocol
    http:ClientHttp2Settings http2Settings = {};
    # The maximum time to wait (in seconds) for a response before closing the connection
    decimal timeout = 30;
    # The choice of setting `forwarded`/`x-forwarded` header
    string forwarded = "disable";
    # Configurations associated with Redirection
    http:FollowRedirects followRedirects?;
    # Configurations associated with request pooling
    http:PoolConfiguration poolConfig?;
    # HTTP caching related configurations
    http:CacheConfig cache = {};
    # Specifies the way of handling compression (`accept-encoding`) header
    http:Compression compression = http:COMPRESSION_AUTO;
    # Configurations associated with the behaviour of the Circuit Breaker
    http:CircuitBreakerConfig circuitBreaker?;
    # Configurations associated with retrying
    http:RetryConfig retryConfig?;
    # Configurations associated with cookies
    http:CookieConfig cookieConfig?;
    # Configurations associated with inbound response size limits
    http:ResponseLimitConfigs responseLimits = {};
    # SSL/TLS-related options
    http:ClientSecureSocket secureSocket?;
    # Proxy server related options
    http:ProxyConfig proxy?;
    # Provides settings related to client socket configuration
    http:ClientSocketConfig socketConfig = {};
    # Enables the inbound payload validation functionality which provided by the constraint package. Enabled by default
    boolean validation = true;
    # Enables relaxed data binding on the client side. When enabled, `nil` values are treated as optional, 
    # and absent fields are handled as `nilable` types. Enabled by default.
    boolean laxDataBinding = true;
|};
